// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJdzOWfpTx1H4laUcHwJwNw8bztTcnjSg',
    appId: '1:523009851660:web:42004ec94c10e8e62d4929',
    messagingSenderId: '523009851660',
    projectId: 'fangre-88927',
    authDomain: 'fangre-88927.firebaseapp.com',
    storageBucket: 'fangre-88927.appspot.com',
    measurementId: 'G-S7S6KKXJES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqSLrG-9qP3_ANMboCbDkqi7hjya2ejxE',
    appId: '1:523009851660:android:3c5c18831a6a11e52d4929',
    messagingSenderId: '523009851660',
    projectId: 'fangre-88927',
    storageBucket: 'fangre-88927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7OrkM0OyFoYq6fvAhQV9UM-J0blnAaWI',
    appId: '1:523009851660:ios:1ba611830cf8de4b2d4929',
    messagingSenderId: '523009851660',
    projectId: 'fangre-88927',
    storageBucket: 'fangre-88927.appspot.com',
    iosClientId: '523009851660-tc80o8ei2psv38nu4v02vaqm02hc0dvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.gazApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7OrkM0OyFoYq6fvAhQV9UM-J0blnAaWI',
    appId: '1:523009851660:ios:112950d4f5757b902d4929',
    messagingSenderId: '523009851660',
    projectId: 'fangre-88927',
    storageBucket: 'fangre-88927.appspot.com',
    iosClientId: '523009851660-mkrok53bvgtiv1rd88i549nhjjpihlpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gazApp.RunnerTests',
  );
}
